application: gmp4ever
version: 1
runtime: python
api_version: 1

handlers:
- url: /
  static_files: gmprss.xml 
  upload: gmprss.xml

- url: /rss.*
  script: rss.py

- url: /BeautifulSoup.*
  script: BeautifulSoup.py
