application: gmp4ever
version: 1
runtime: python
api_version: 1

handlers:
- url: /gmp\/rss\.xml
  static_files: gmprss.xml 
  upload: gmprss.xml

- url: /BeautifulSoup.*
  script: BeautifulSoup.py

- url: /.*
  script: rss.py

